//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websiteLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int pID { get; set; }
        public string pTc { get; set; }
        public string pAd { get; set; }
        public string pSoyad { get; set; }
        public string pTel { get; set; }
        public string pCinsiyet { get; set; }
        public string pDogumYeri { get; set; }
        public Nullable<System.DateTime> pDogumTarih { get; set; }
    }
}
